
---
title: "BlueBikes"
author: "Tyler Kindy"
date: "March 22, 2019"
output: pdf_document
---

```{r}
library(tidyverse)
library(lubridate)
bikes <- read_csv("data/bluebikes.csv") %>%
  mutate(
    startday = date(starttime),
    starthour = hour(starttime),
    stopday = date(stoptime),
    stophour = hour(stoptime)
  )
bikes
```

```{r}
bikes %>%
  group_by(`start station id`, `end station id`) %>%
  summarize(count = n()) %>%
  arrange(-count)
```

```{r}
genders = bikes %>%
  group_by(usertype, gender) %>%
  summarize(count = n())
genders
```

Genders:
  0 - unknown
  1 - male
  2 - female

```{r}
starts = bikes %>%
  select(station_id = `start station id`, name = `start station name`, lat = `start station latitude`, lon = `start station longitude`)
ends = bikes %>%
  select(station_id = `end station id`, name = `end station name`, lat = `end station latitude`, lon = `end station longitude`)
stations = bind_rows(starts, ends) %>%
  distinct(station_id, .keep_all = TRUE) %>%
  arrange(station_id)
stations
```

```{r}
start_trips = bikes %>%
  group_by(`start station id`, usertype) %>%
  summarize(count = n()) %>%
  rename(station_id = `start station id`)
end_trips = bikes %>%
  group_by(`end station id`, usertype) %>%
  summarize(count = n()) %>%
  rename(station_id = `end station id`)
usertype_trips = bind_rows(start_trips, end_trips) %>%
  group_by(station_id, usertype) %>%
  summarize(count = sum(count))
cust_trips = usertype_trips %>%
  filter(usertype == "Customer")
sub_trips = usertype_trips %>%
  filter(usertype == "Subscriber")
usertype_ratios = cust_trips %>%
  inner_join(sub_trips, by = c("station_id"), suffix = c("_cust", "_sub")) %>%
  select(station_id, count_cust, count_sub) %>%
  mutate(ratio = count_cust / (count_cust + count_sub)) %>%
  select(station_id, ratio)
usertype_ratios %>%
  arrange(station_id)
```

```{r}
library(ggmap)
station_ratios = stations %>%
  inner_join(usertype_ratios)
station_ratios
```

```{r}
get_googlemap(
  "42.334885,-71.086294", zoom = 12, maptype = "roadmap",
  style = c(feature = "poi", visibility = "off")
) %>%
  ggmap() +
  geom_point(aes(x = lon, y = lat, size = ratio), alpha = 0.4, data = station_ratios) +
  labs(size = "Customer Trips / Total")
  theme_void()
```

```{r}
get_googlemap(
  "42.345,-71.075", zoom = 13, maptype = "roadmap",
  style = c(feature = "poi", visibility = "off")
) %>%
  ggmap() +
  geom_point(aes(x = lon, y = lat, size = ratio), alpha = 0.4, data = station_ratios) +
  labs(size = "Customer Trips / Total")
  theme_void()
```

```{r}
bikes_sliced = bikes[c(1:50000),]

morning_bikes = bikes_sliced %>%
  filter(starthour > 6) %>%
  filter(starthour < 10)

get_googlemap(
  "42.345,-71.075", zoom = 12, maptype = "roadmap",
  style = c(feature = "poi", visibility = "off")
) %>%
  ggmap() +
  geom_point(aes(x = `start station longitude`, y = `start station latitude`), alpha = 0.04, color="red", data = morning_bikes, position = position_jitter(width = 0.006, height = 0.006)) +
  geom_point(aes(x = `end station longitude`, y = `end station latitude`), alpha = 0.03, color="blue", data = morning_bikes, position = position_jitter(width = 0.006, height = 0.006)) +
  theme_void()
```

```{r}
evening_bikes = bikes_sliced %>%
  filter(starthour > 15) %>%
  filter(starthour < 19)

get_googlemap(
  "42.345,-71.075", zoom = 12, maptype = "roadmap",
  style = c(feature = "poi", visibility = "off")
) %>%
  ggmap() +
  geom_point(aes(x = `start station longitude`, y = `start station latitude`), alpha = 0.02, color="red", data = evening_bikes, position = position_jitter(width = 0.006, height = 0.006)) +
  geom_point(aes(x = `end station longitude`, y = `end station latitude`), alpha = 0.015, color="blue", data = evening_bikes, position = position_jitter(width = 0.006, height = 0.006)) +
  theme_void()
```

```{r}
real_users = bikes %>%
  filter(`birth year` != "NULL") %>%
  mutate(`birth year` = parse_integer(`birth year`)) %>%
  filter(!(`birth year` == 1969 & gender == 0))
real_users %>%
  mutate(birth_decade = trunc(`birth year` / 10) * 10) %>%
  group_by(birth_decade) %>%
  summarize(count = n()) %>%
  arrange(-count)
```

```{r}
real_users %>%
  group_by(`birth year`) %>%
  summarize(count = n()) %>%
  arrange(-count)
```

```{r}
real_users %>%
  ggplot() +
  geom_bar(aes(x = `birth year`))
```

```{r}
real_users <- real_users %>%
  filter(`birth year` >= 1920)

real_users %>%
  ggplot() +
  geom_bar(aes(x = `birth year`)) +
  labs(
    title = "Birth Year of Users Born After 1920",
    x = "Birth Year",
    y = "Number of Users"
  )
```

```{r}
genders_start = real_users %>%
  group_by(`start station id`, gender) %>%
  summarize(count = n()) %>%
  rename(station_id = `start station id`)
genders_end = real_users %>%
  group_by(`end station id`, gender) %>%
  summarize(count = n()) %>%
  rename(station_id = `end station id`)
genders = genders_start %>%
  inner_join(genders_end, by = c("station_id", "gender"), suffix = c("_start", "_end")) %>%
  select(station_id, gender, count_start, count_end) %>%
  mutate(trips = count_start + count_end) %>%
  select(station_id, gender, trips) %>%
  arrange(station_id)

install.packages("reshape")
library("reshape")
genders <- cast(genders, station_id~gender)
genders
```

```{r}
ages_start = real_users %>%
  mutate(birth_decade = trunc(`birth year` / 10) * 10) %>%
  group_by(`start station id`, birth_decade) %>%
  summarize(count = n()) %>%
  dplyr::rename(station_id = `start station id`)
ages_end = real_users %>%
  mutate(birth_decade = trunc(`birth year` / 10) * 10) %>%
  group_by(`end station id`, birth_decade) %>%
  summarize(count = n()) %>%
  dplyr::rename(station_id = `end station id`)
ages = ages_start %>%
  inner_join(ages_end, by = c("station_id", "birth_decade"), suffix = c("_start", "_end")) %>%
  select(station_id, birth_decade, count_start, count_end) %>%
  mutate(trips = count_start + count_end) %>%
  select(station_id, birth_decade, trips) %>%
  arrange(station_id)
ages <- cast(ages, station_id~birth_decade)
ages
bucket_date <- function(time) {
  bucket <- floor_date(time, unit = "30 minutes")
  year(bucket) <- 1900
  month(bucket) <- 1
  day(bucket) <- 1
  bucket
}

time_buckets = bikes %>%
  mutate(
    start_bucket = bucket_date(starttime),
    end_bucket = bucket_date(stoptime)
  ) %>%
  select(`start station id`, `end station id`, start_bucket, end_bucket)
```

```{r}
start_buckets = time_buckets %>%
  group_by(`start station id`, start_bucket) %>%
  summarize(count = n())

end_buckets = time_buckets %>%
  group_by(`end station id`, end_bucket) %>%
  summarize(count = n())

start_buckets
```

```{r}
grouped_buckets = start_buckets %>%
  inner_join(end_buckets, by = c("start station id" = "end station id", "start_bucket" = "end_bucket")) %>%
  select(station_id = `start station id`, bucket = start_bucket, start_count = count.x, end_count = count.y)
```

```{r}
grouped_buckets %>%
  arrange(-end_count)
```
